### PR TITLE
Update to Jetty 12.0.8 and Jersey 3.1.6

### PR DESCRIPTION
**Pull request by jvanzyl**

### CODE REVIEW

**Comment by asafm** [comment]
@ofir-popowski Hey man - can you take a look? It looks good to me but we need to run the build.

**Review by ordaniel888 — APPROVED** [review]

**Comment by asafm** [comment]
@ordaniel888 Can you take care of the build so this can be merged?

**Comment by celtric** [comment]
Any update on this one? We're having `java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/HandlerWrapper` which I understand this PR addresses.

**Comment by ordaniel888** [comment]
We have made the decision to no longer maintain this open-source project. You’re welcome to fork it and continue its development or publish it as you see fit

**Comment by celtric** [comment]
> We have made the decision to no longer maintain this open-source project. You’re welcome to fork it and continue its development or publish it as you see fit

Thanks for the update @ordaniel888. We decided to write our own glue code based on this repository, as we understood that the nature of it will not allow to cover all possible combinations of versions without generating a matrix of artifacts. Using this repository as a reference was of huge help, thank you for that!

**Pull request closed without merging**
