### PR TITLE
Migrate from javax package to jakarta

### PR DESCRIPTION
**Pull request by kdombeck**
This [issue](https://github.com/google/guice/issues/1383) was a long time in the making. 

This PR upgrades to [Guice 7.0](https://github.com/google/guice/wiki/Guice700)

### CODE REVIEW

**Comment by kdombeck** [comment]
@ofir-popowski Is there a possibility of having this reviewed and merged?

Thank you

**Comment by kdombeck** [comment]
@ofir-popowski would you be able to look at this PR? thanks

**Review by ofir-popowski — APPROVED** [review]
@kdombeck Thank you very much for this, and I apologize for the late reply 🙏🏻 
I'm going to (try to) merge and cut a release from this

I should point out that we're not actively maintaining this library anymore. I will see about making you a maintainer or collaborator on this repository (if you're interested)

**Comment by kdombeck** [comment]
@ofir-popowski thank you so much!!

I will gladly be a maintainer/collaborator. Let me know what I need to do.

**Comment by ofir-popowski** [comment]
@kdombeck okay so here's the thing, as mentioned before we are not maintaining this library at all, and have deprecated it internally in our organization. Additionally, I'm sorry to say we cannot accept members / collaborators to our OS projects at this time

So we have 2 options
1. We can keep what we have done so far. You can keep submitting PRs and we'll review and cut release when we have some time
2. You can fork this and maintain it independently (changing the group id away from `io.logz`), and setup publishing to a central repository. We will update the README in this repository to point to your fork and note this one as deprecated / unmaintained

Please let me know which of those you find agreeable, and I'd like to thank you for all of your contributions so far :)

**Comment by kdombeck** [comment]
I'm fine with option 1. Since this is the repo that shows up in Google search results.

I can take any issues or PRs that other people submit to this project.

**Pull request merged**
